### ISSUE TITLE
Application not available in playstore

### ISSUE THREAD

**Issue by denvash** [denvash/Jesta#8]
App not available on playstore

_Originally posted by @maaudrana in https://github.com/denvash/jesta-android-app/issues/6#issuecomment-493742481_

**Comment by masudr4n4** [comment]
is there any chance to add again to playstore?

**Comment by denvash** [comment]
We added the .apk file to [the releases page](https://github.com/denvash/jesta-android-app/releases/download/2.0.4/Jesta.1.0.7_11.apk).
